version: "3"
services:
  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSGTRES_USER=leif_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pj_manager_development
