version: "3"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    entrypoint: ./docker-rails.sh
    environment:
      RAILS_ENV: 'development'
      VITE_RUBY_HOST: vite
      REDIS_HOST: redis
      REDIS_PORT: 6380
      REDIS_DB: 0
    ports:
      - 3000:3000
    volumes:
      - .:/project-manager
    depends_on:
      - db
      - vite
      - redis
    tty: true
    stdin_open: true
  vite:
    build:
      context: .
      dockerfile: dev.Dockerfile
    entrypoint: ./docker-vite.sh
    environment:
      RAILS_ENV: 'development'
      DEBUG: '*vite*'
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/project-manager
  db:
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pj_manager_development
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0
    restart: always
    command: redis-server --port 6380
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  postgres:
  redis: