version: "3"
services:
  app:
    build: .
    entrypoint: ./docker-rails.sh
    environment:
      RAILS_ENV: development
      VITE_RUBY_HOST: vite
    ports:
      - 3000:3000
    volumes:
      - .:/project-manager
    depends_on:
      - db
      - vite
  vite:
    build: .
    entrypoint: ./docker-vite.sh
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/project-manager
  db:
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pj_manager_development
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: