version: "3"
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/project-manager
    depends_on:
      - db
      - vite
  vite:
    image: node:16.0.0
    entrypoint: /bin/bash
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    working_dir: /project-manager/app/javascript
    ports:
      - "3036:3036"
    volumes:
      - .:/project-manager/app
    stdin_open: true
    tty: true
  db:
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pj_manager_development
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: