export { default as BoardsPage } from './BoardsPage'
export { default as Home } from './Home'
export { default as SignUpPage } from './user/SignUpPage'
export { default as ProfilePage } from './user/ProfilePage'
export { default as ProjectsPage } from './project/ProjectsPage'
